Repository Onemind-Services-LLC/netbox-metatype-importer, pull requests merged in 2024-10, with the labels that each got.

#54 NB-70 Fixed Matching Query and Bulk Deletion Issue
  netbox_metatype_importer/views.py
Labels: type: bug

#57 OMS-393 Bulk Delete Issue Resolved for Netbox v4
  netbox_metatype_importer/views.py
  setup.py
Labels: type: bug

#58 Release v0.4.1
  CHANGELOG.md
  netbox_metatype_importer/views.py
  setup.py
Labels: type: release

#56 OMS-369 Support Added for NetBox v4.1
  Dockerfile
  README.md
  netbox_metatype_importer/__init__.py
  netbox_metatype_importer/api/serializers.py
  netbox_metatype_importer/api/urls.py
  netbox_metatype_importer/api/views.py
  netbox_metatype_importer/tests/test_models.py
  netbox_metatype_importer/utils.py
  netbox_metatype_importer/views.py
  setup.py
Labels: type: feature
